version: 2
jobs:
  build:
    working_directory: ~/rabbithole
    docker:
      - image: python:3.6.0
    steps:
      - checkout
      - restore_cache:
          key: rabbithole-{{ .Branch }}
      - run: apt update
      - run: apt install -y gcc python-dev
      - run: pip install tox
      - run: tox
      - save_cache:
          key: rabbithole-{{ .Branch }}
          paths:
            - ~/rabbithole/.tox
