version: 2
jobs:
  build:
    working_directory: ~/rabbithole
    docker:
      - image: python:3.6.0
    steps:
      - checkout
      - run: apt update
      - run: apt install -y gcc python-dev
      - run: pip install tox
      - run: tox
