version: 2
jobs:
  build:
    working_directory: ~/rabbithole
    docker:
      - image: python:3.6.0
    parallelism: 4
    steps:
      - checkout
      - restore_cache:
          key: rabbithole-{{ .Branch }}-{{ .Environment.CIRCLE_NODE_INDEX }}
      - run: apt update
      - run: apt install -y gcc python-dev
      - run: pip install tox
      - run: |
          set -e
          case $CIRCLE_NODE_INDEX in
          0)
            tox -e py27
            tox -e py36
            ;;
          1)
            tox -e flake8
            ;;
          2)
            tox -e mypy2
            ;;
          3)
            tox -e mypy3
            ;;
          esac
      - save_cache:
          key: rabbithole-{{ .Branch }}-{{ .Environment.CIRCLE_NODE_INDEX }}-{{ checksum "requirements/common.txt" }}
          paths:
            - ~/rabbithole/.tox
